### ISSUE TITLE
Server crash still happening [1.18.2]

### ISSUE THREAD

**Issue by BugmanBugman** [Toadstool-Studios/Lil-Wings#3]
https://gist.github.com/BugmanBugman/0d228abd5c9374097fce9ba90feff994

**Comment by Leonime** [comment]
Got the same problem, Looks like the problem seems to be that this mod requires the geckolib, but that library can't run on server.

[latest.log](https://github.com/terrarium-earth/Lil-Wings/files/8865659/latest.log)
