### ISSUE TITLE
[BUG] Lil' wings 1.18.2, Server Crash Null Error.

### ISSUE THREAD

**Issue by CKY-** [Toadstool-Studios/Lil-Wings#8]
During some gameplay on a server, player placed a bottle on top of a trees leaf block and broke the jar which resulted in null error. 
https://gist.github.com/CKY-/35c50c8587bbd2bdf57c6dc4af2bc103

Forge: net.minecraftforge:40.1.68
lilwings-forge-1.18.2-1.2.2.jar                   |Lil' Wings                    |lilwings                      |1.2.2

Update: placing the jar on grass produced the same issue

**Comment by CKY-** [comment]
I see this was fixed and thank you for fixing it. 
I do see forge is in the repo still but was there a decision made to stop supporting forge all together?
I see 2 updates to fabric for 1.2.3? tried reaching out on curse, maybe here is a better place?

We do like this mod and what it adds to the landscape. I hope that you do continue to support forge.

**Comment by CodexAdrian** [comment]
The lack of a forge jar is completely unintentional, i had to found an issue in the middle of uploading my jar, so i uploaded another one with the issue fixed and i forgot to upload the forge jar. i havent gotten around to upload it, but rest assured i will continue to support forge
